######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 19:02:44 2016
######################################################################

QT += core testlib
CONFIG += testcase

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += ../src/character.h \
           ../src/chapter.h \
           ../src/completable.h \
           ../src/scene.h \
           ../src/novel.h \
            ../src/plotline.h \
            ../src/serializable.h \
            tst_chapter.h \
            tst_character.h \
            tst_novel.h \
            tst_scene.h \
    tst_novel.h \
    tst_scene.h \
    tst_plotline.h

SOURCES += main.cpp \
           tst_chapter.cpp \
           tst_character.cpp \
           tst_novel.cpp \
           tst_scene.cpp \
           ../src/character.cpp \
           ../src/chapter.cpp \
           ../src/completable.cpp \
           ../src/scene.cpp \
           ../src/novel.cpp \
            ../src/plotline.cpp \
            ../src/serializable.cpp\
    tst_plotline.cpp

QMAKE_CXXFLAGS += -std=gnu++11

DISTFILES += \
    fixtures/chapter-deserialize.json \
    fixtures/character-deserialize.json \
    fixtures/novel-deserialize.json
