######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 18:51:06 2016
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

#QT       += testlib core gui
#greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

#TARGET = testPlotline
#CONFIG   += console
#CONFIG   -= app_bundle

#TEMPLATE = app

#SOURCES += ../src/chapter.cpp \
#           ../src/character.cpp \
#           ../src/completable.cpp \
#           ../src/main.cpp \
#           ../src/mainwindow.cpp \
#           ../src/novel.cpp \
#           ../src/plotline.cpp \
#           ../src/scene.cpp \
#           ../src/sceneitemmodel.cpp

# Input
HEADERS += ../src/character.h \
           ../src/chapter.h \
           ../src/completable.h \
           ../src/scene.h \
           ../src/novel.h \

SOURCES += main.cpp \
           tst_chapter.cpp \
           tst_character.cpp \
           tst_novel.cpp \
           tst_scene.cpp \
           ../src/character.cpp \
           ../src/chapter.cpp \
           ../src/completable.cpp \
           ../src/scene.cpp \
           ../src/novel.cpp
