######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 19:02:44 2016
######################################################################

TEMPLATE = subdirs

SUBDIRS += unit \
    integration \

CONFIG += -std=gnu++11
