######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 19:04:32 2016
######################################################################

TEMPLATE = subdirs
TARGET = Plotline

SUBDIRS = src \
    test \
    doc

