######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 18:57:44 2016
######################################################################

TEMPLATE = subdirs

SUBDIRS += \
    lib \
    app \
    data

RESOURCES += \
    res/plotline.qrc

CONFIG += gnu++11

app.depends = libs app
test.depends = libs app
