######################################################################
# Automatically generated by qmake (3.0) Tue Jan 19 18:57:44 2016
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS += \
    lib \
    app

CONFIG += gnu++11

app.depends = lib
test.depends = lib app
